packages:
  - "packages/*"
  - "extensions/*"

minimumReleaseAgeExclude:
  - "@earendil-works/*"
  - "@nielpattin/*"
  - "@mariozechner/*"
  - '@plannotator/pi-extension'
  - '@plannotator/webtui@0.1.0'
  - '@cortexkit/*'
  - '@ff-labs/*'
  - '@aws-sdk/*'
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@rolldown/*"
  - "@smithy/*"
  - oxlint
  - oxfmt
allowBuilds:
  "@google/genai": true
  esbuild: true
  koffi: true
  msgpackr-extract: true
  protobufjs: true
  better-sqlite3: true
  tree-sitter-bash: true
  onnxruntime-node: true
  sharp: true

# Supply chain security
minimumReleaseAge: 0

# blockExoticSubdeps: true

# Extra hardening (recommended in v11)
# strictDepBuilds: true
